version: '3'
services:
  debian-cli:
    image: debian-cli:v0.1.1.2
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      - PROMPT_COMMAND='history -a' # Immediately persist commands to .bash_history                                                                                                                                                                                                                                │
      - HISTSIZE=100000 # Number of lines to keep for history command                                                                                                                                                                                                                                              │
      - HISTFILESIZE=100000000 # Number of lines to keep for ~/.bash_history
    volumes:
      - ./home:/root/
      - ./opt:/opt/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
