version: '3'
services:
  debian-cli:
    image: debian-cli:v0.1.1.2
    ports:
      - "0.0.0.0:9000-9030:9000-9030"
      - "0.0.0.0:8000-8019:8000-8019"
      - "0.0.0.0:8021-8030:8021-8030"
      - "0.0.0.0:8031-8045:8031-8045"
          
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    entrypoint: bash /opt/start/entrypoint.sh
    volumes:
      - ./home:/root/
      - ./opt:/opt/
      - $HOME/.kube/:/root/.kube/
      - $HOME/.aws/:/root/.aws/
      - ./entrypoint.sh:/opt/start/entrypoint.sh
      - ./env.sh:/opt/start/env.sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t
